version: '1.0'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: flawas/weblab-backend:latest
    container_name: weblab-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/techradardb

  frontend:
    image: flawas/weblab-frontend:latest
    container_name: weblab-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mongo-data: